# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('portfolio', '0001_initial'), ('portfolio', '0002_work_discipline'), ('portfolio', '0003_performance'), ('portfolio', '0004_auto_20170605_2338'), ('portfolio', '0005_auto_20170606_0000'), ('portfolio', '0006_auto_20170606_0005'), ('portfolio', '0007_auto_20170606_0007'), ('portfolio', '0008_auto_20170606_0022'), ('portfolio', '0009_auto_20170606_0351'), ('portfolio', '0010_remove_performance_location'), ('portfolio', '0011_auto_20170606_0433'), ('portfolio', '0012_work_slug'), ('portfolio', '0013_auto_20170608_2141'), ('portfolio', '0014_work_slug'), ('portfolio', '0015_auto_20170608_2208'), ('portfolio', '0016_auto_20170608_2208'), ('portfolio', '0017_auto_20170608_2211'), ('portfolio', '0018_auto_20170611_0146'), ('portfolio', '0019_auto_20170611_0931'), ('portfolio', '0020_tag'), ('portfolio', '0021_auto_20170611_1145'), ('portfolio', '0022_tag_slug'), ('portfolio', '0023_auto_20170612_1832'), ('portfolio', '0024_auto_20170612_2056'), ('portfolio', '0025_work_text2'), ('portfolio', '0026_remove_work_text2'), ('portfolio', '0027_auto_20170622_2310'), ('portfolio', '0028_images_title'), ('portfolio', '0029_auto_20170622_2336'), ('portfolio', '0030_auto_20170623_1646'), ('portfolio', '0031_auto_20170624_0651'), ('portfolio', '0032_auto_20170624_0654'), ('portfolio', '0033_auto_20170624_1841'), ('portfolio', '0034_work_pdf'), ('portfolio', '0035_work_abstract'), ('portfolio', '0036_image_image_type'), ('portfolio', '0037_auto_20170707_0453'), ('portfolio', '0038_auto_20170707_1734'), ('portfolio', '0039_work_thumbnail'), ('portfolio', '0040_auto_20170711_2211'), ('portfolio', '0041_auto_20170711_2214'), ('portfolio', '0042_auto_20170711_2315'), ('portfolio', '0043_auto_20170712_1926'), ('portfolio', '0044_remove_image_description'), ('portfolio', '0045_work_clip'), ('portfolio', '0046_video'), ('portfolio', '0047_auto_20170713_0651'), ('portfolio', '0048_auto_20170713_1551'), ('portfolio', '0049_auto_20170713_1748'), ('portfolio', '0050_auto_20170713_2108'), ('portfolio', '0051_auto_20170713_2130'), ('portfolio', '0052_audio')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('text', models.TextField()),
                ('created_date', models.DateField()),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='tags',
            field=models.ManyToManyField(blank=True, to='portfolio.Tag'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('title', models.CharField(default='imageya', max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='images',
            field=models.ManyToManyField(blank=True, to='portfolio.Image'),
        ),
        migrations.AddField(
            model_name='work',
            name='featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='work',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='pdf',
            field=models.FileField(blank=True, upload_to='pdfs'),
        ),
        migrations.AddField(
            model_name='work',
            name='abstract',
            field=models.TextField(max_length=200),
        ),
        migrations.AddField(
            model_name='work',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnails'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Venue')),
                ('other', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='vimeo',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='work',
            name='youtube',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='work',
            field=models.ManyToManyField(blank=True, to='portfolio.Work'),
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('upload', models.FileField(upload_to='audio')),
            ],
        ),
    ]
