# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-10 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='title',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='upload',
        ),
        migrations.AddField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='audio'),
        ),
        migrations.AddField(
            model_name='audio',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
