# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='discipline',
            field=models.CharField(default='art', max_length=50),
            preserve_default=False,
        ),
    ]
