# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-06 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='archive',
            field=models.FileField(blank=True, upload_to='archive'),
        ),
    ]
