# Generated by Django 4.2.3 on 2023-11-08 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='thumbnail',
        ),
    ]
