# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-10 03:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20170910_0307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='audio_file',
            new_name='audio',
        ),
    ]
