# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-10 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20170910_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Audio'),
        ),
    ]
