# Generated by Django 5.2.17 on 2026-10-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_work_mainimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='body',
            field=models.TextField(blank=True, help_text='New-style page in Markdown with {image: title}, {audio: title}, {vimeo: id} and {youtube: id} lines. When filled in, it replaces the old layout.'),
        ),
    ]
