# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20170605_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Work'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Venue'),
        ),
    ]
