# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-10 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_work_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='name',
        ),
        migrations.AddField(
            model_name='audio',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='work',
            name='audio',
        ),
        migrations.AddField(
            model_name='work',
            name='audio',
            field=models.ManyToManyField(blank=True, to='portfolio.Audio'),
        ),
    ]
