# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20170606_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='work',
        ),
        migrations.AddField(
            model_name='work',
            name='tag',
            field=models.ManyToManyField(to='portfolio.Tag'),
        ),
    ]
