# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 00:22
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20170606_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='tag',
        ),
        migrations.AddField(
            model_name='work',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, null=True), null=True, size=None),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
