# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_remove_performance_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='date',
            field=models.DateField(),
        ),
    ]
