# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_work_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='slug',
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
