# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_work_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', editable=False),
        ),
    ]
