# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_auto_20170608_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
