# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_auto_20170608_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='event',
            field=models.CharField(default='Some Name', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
