# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_auto_20170611_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('works', models.ManyToManyField(to='portfolio.Work')),
            ],
        ),
    ]
