# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='works',
        ),
        migrations.AddField(
            model_name='work',
            name='tags',
            field=models.ManyToManyField(to='portfolio.Tag'),
        ),
    ]
