# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_auto_20170612_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
