# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_work_text2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='text2',
        ),
    ]
