# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_remove_work_text2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='miscellany/work/')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='work',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='work',
            name='images',
            field=models.ManyToManyField(to='portfolio.Images'),
        ),
    ]
