# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_auto_20170622_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='title',
            field=models.CharField(default='imageya', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
