# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0030_auto_20170623_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='work',
            name='github',
            field=models.URLField(blank=True),
        ),
    ]
