# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0032_auto_20170624_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='performance',
            name='other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='performance',
            name='work',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Work'),
        ),
        migrations.AddField(
            model_name='performance',
            name='collaborators',
            field=models.ManyToManyField(to='portfolio.Collaborator'),
        ),
    ]
