# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0033_auto_20170624_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='pdf',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
