# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0034_work_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='abstract',
            field=models.TextField(default='This is a filler abstract description'),
            preserve_default=False,
        ),
    ]
