# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0035_work_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_type',
            field=models.CharField(choices=[('W', 'wor'), ('P', 'profile')], default='W', max_length=1),
        ),
    ]
