# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0036_image_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_type',
            field=models.CharField(choices=[('W', 'Work'), ('P', 'Profile')], default='W', max_length=1),
        ),
    ]
