# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0038_auto_20170707_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='', verbose_name=portfolio.models.Image),
        ),
    ]
