# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0042_auto_20170711_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_type',
            field=models.CharField(choices=[('W', 'Work'), ('P', 'Profile'), ('G', 'GitHub')], default='W', max_length=1),
        ),
    ]
