# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 23:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0043_auto_20170712_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
    ]
