# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0044_remove_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='clip',
            field=models.URLField(blank=True),
        ),
    ]
