# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0046_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='clip',
        ),
        migrations.AddField(
            model_name='work',
            name='clips',
            field=models.ManyToManyField(blank=True, to='portfolio.Video'),
        ),
    ]
