# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0047_auto_20170713_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='clips',
        ),
        migrations.AddField(
            model_name='work',
            name='vimeo',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='work',
            name='youtube',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
