# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0048_auto_20170713_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_type',
            field=models.CharField(max_length=1),
        ),
    ]
