# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0050_auto_20170713_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RemoveField(
            model_name='event',
            name='work',
        ),
        migrations.AddField(
            model_name='event',
            name='work',
            field=models.ManyToManyField(blank=True, to='portfolio.Work'),
        ),
        migrations.AlterField(
            model_name='work',
            name='abstract',
            field=models.TextField(max_length=200),
        ),
    ]
