# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0051_auto_20170713_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('upload', models.FileField(upload_to='audio')),
            ],
        ),
    ]
